# kubectl apply -f 8.1job.yaml
# kubectl get pods -w
# kubectl delete jobs pi

apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  parallelism: 2 # 10 adet Pod oluşturulacak ve bunları 2 şer 2 şer oluşturacak.
  completions: 10 # Bu Job altında kaç tane başaralı pod oluşturmak istedğimizi belirtiyoruz
  backoffLimit: 5 # Podlar oluşturulurken toplamda 5 kezden fazla fail olursa Job ile pod oluşturmayı durdur.
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never #OnFailure 